### ISSUE TITLE
Can't get orders, positions or wallets 

### ISSUE THREAD

**Issue by FelipeSBonetto** [nlsdfnbch/btfxwss#24]
Hi, 
I can place orders fine but the code:
`wss = BtfxWss(key, secret)`
`wss.start()`
`wss.authenticate()`
`wss.orders.empty()`

Always returns True, how can I get my orders, positions and wallets using btfxwss?

**Comment by nlsdfnbch** [comment]
Hey @FelipeSBonetto and thanks for reporting this issue!
I need a few more details to help you out:

 1. Can you confirm that authentication works? Are there any errors raised or logged?
 2. Confirm that you are receiving data on the other authenticated channels (as a reference, check [this file](https://github.com/nlsdfnbch/btfxwss/blob/master/btfxwss/client.py), starting at line 58, to see what private channels you can try polling). If all are empty, there may be something wrong with the authentication. 
 3. Could you run the above code with debugging enabled and attach the log file? You just have to add the following lines and it should work:

```
import logging
logging.basicConfig(filename="btfxwss.log", level=logging.DEBUG)

wss=BtfxWss(key, secret, log_level=logging.DEBUG)
...
```

**Comment by FelipeSBonetto** [comment]
I have a sense that I'm doing something fundamentaly wrong, because I can actually see my balance in the log file. Probably I just don't know how to use the functions.

I'll be happy to help you write a documentation for this code.
  
[btfxwss.txt](https://github.com/nlsdfnbch/btfxwss/files/1246536/btfxwss.txt)

PS.: I saw in other forks a function to see Bids and Offers out of the Order Book. Have this function become discontinued in recent commits? Why?

Thanks!

**Comment by nlsdfnbch** [comment]
Hey @FelipeSBonetto ,
So it turns out that I hadn't implemented the `_handle_account()` method in the main routine of `QueueProcessor` (#28), which is what you can see in the logs (it logs errors for all messages from channel id `0`). I fixed this in my last commit, so give it another try and let me know if this works now - im on vacation atm, and can't verify it myself.

As for the bids and offers:
The client, as it is currently implemented, is just meant to abstract away the process of connecting to the api and receiving the data. That's why all data is provided as it is received via `Queue` objects. These are accessed via properties or methods of `BtfxWss` instances. 

So, to answer your question: You CAN access this data, but it is raw - meaning that you will have to build an order book yourself if you want to see the current bids and asks, for example.

You can get this data by calling these:
```
wss = BtfxWss()
wss.books('BTCUSD')  # Returns order book data for BTCUSD
```

Now that I'm looking at it, it would perhaps be better to make them all available as a property, instead of part method, part property.

**Comment by FelipeSBonetto** [comment]
Hello @nlsdfnbch, thanks for your reply!

I tried to run this code:
`wss.wallets.get()`
but got:
_handle_account() missing 1 required positional argument: 'ts'

Not shure if it's a bug or if it's me. Tried to look for some clues on the code but couldn't figure it out

**Comment by nlsdfnbch** [comment]
That issue should be handled now - PR #30 is now merged into dev, so if you use the `dev` branch it should now work for you!
I'll update the pypi release once i'm back from vacation.
Thanks for your help!
