### ISSUE TITLE
Relationship to nlsdfnbch/bitex?

### ISSUE THREAD

**Issue by lucasb-eyer** [nlsdfnbch/btfxwss#37]
Hi, after stalking you a little, I noticed your other project nlsdfnbch/bitex. It seems to be, or at least become a superset of this one. What are your plans? Why not link to the other one in the README? Anyways, thanks for both projects!

Cheers!

**Comment by nlsdfnbch** [comment]
Hehe ;D bitex started out as a REST API framework and starting with 2.0 will be purely REST again (i had added websocket clients at some point,  but couldn't figure out a good way to standardise them then). 

Btfxwss is a websocket client and thus doesn't fit the framework. 

I'm keeping it separate,  because I have not yet found a good way to refactoring websocket connections for other exchanges. The use of a variety of protocols and libraries simply makes it a pain in the ass.

As for the link in the reader,  it just never occurred to me :D

**Comment by lucasb-eyer** [comment]
Thanks for the clarification, it makes a lot of sense. Closing this issue, as it's not really an issue.
