### ISSUE TITLE
order book processing

### ISSUE THREAD

**Issue by Prokhozhijj** [nlsdfnbch/btfxwss#55]
Hi,
It looks like current version of BtfxWss.subscribe_to_order_book and BtfxWss.unsubscribe_from_order_book does not process at all such parameters as precision, frequency and length. Of course they can be transferred via **kwargs. But, for example, BtfxWss.subscribe_to_raw_order_book and BtfxWss.unsubscribe_from_raw_order_book have parameter "prec". 
I am not sure it is a bug but all these discrepancies between those procedures look strange from design point of view.

**Comment by nlsdfnbch** [comment]
Hey @Prokhozhijj,
thanks for contributing!
It is indeed not a bug - the precision parameter is passed because it's needed to specify that you'd like the raw book (precision being `R0` instead of `P0`), which is why they're present in both. 

I agree, however, that the design choices for the client methods is  wonky. I'm currently looking at a better solution. I'll open a separate issue for this, to make this more apparent. 

Thanks for you feedback!
