### ISSUE TITLE
import btfxwss fails

### ISSUE THREAD

**Issue by ppop** [nlsdfnbch/btfxwss#66]
Pip installed the package, tried to import it

`from btfxwss import BtfxWss`

I'm getting the following error:

```
File "/usr/local/lib/python3.4/site-packages/btfxwss/__init__.py", line 1, in <module>
    from btfxwss.client import BtfxWss

  File "/usr/local/lib/python3.4/site-packages/btfxwss/client.py", line 5, in <module>
    from btfxwss.connection import WebSocketConnection

  File "/usr/local/lib/python3.4/site-packages/btfxwss/connection.py", line 450
    self.send(**q, auth=True)
                 ^
SyntaxError: invalid syntax
```

**Comment by nlsdfnbch** [comment]
Hey @ppop !

Thanks for opening an issue. 
What Python version are you using?

**Comment by nlsdfnbch** [comment]
Hey @ppop !

Thanks for opening an issue.

The error you're seeing here is due to an unsupported Python version (`BtfxWss` only works with python 3.5+), since it uses[ starred expression unpacking in function calls](https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-448). 
If you like, you can submit a PR that fixes this and makes it compatible to earlier Python3 versions.

Cheers,

Nils
