### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by rchiossi** [nlsdfnbch/btfxwss#68]
Hi, 
I just installed btfxwss for the first time and I'm trying to run the sample code in the README file. The code executes, but is unable to connect. I get the following error:

```
INFO:btfxwss.connection:Connection Error - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
INFO:btfxwss.connection:Connection closed
INFO:btfxwss.connection:Attempting to connect again in 10 seconds.
```

I'm running the code on Ubuntu 16.04 with python 3.5.2

Any idea what may be causing the issue?

**Comment by nlsdfnbch** [comment]
Hey @rchiossi !

Thanks for submitting an issue!

The error you're seeing is due to an unverified Certificate on Bitfinex's side (which is worrisome, but not fixable on my end, unfortunately). 

See here for more details:
https://stackoverflow.com/questions/34503206/ssl-certificate-verify-failed-python

**Comment by rchiossi** [comment]
Hmm, that's really bad indeed! 
Thanks for helping, I'll try to work a way around it.

**Comment by ShelMX** [comment]
Like you, I faced the same problem.
Did you solve this problem?
If so, what helped you?)
