### ISSUE TITLE
Error Handler Reconnection

### ISSUE THREAD

**Issue by Changsung** [nlsdfnbch/btfxwss#94]
Hello @nlsdfnbch, 

I have a reconnection issue for an unknown error code in error_handler in connection.py. 
When the socket receives an unknown error(In my case, {'msg': 'user: invalid', 'code': 20000} ) in a message, the connection should be reconnected. But there is no reconnection code in the current version.
I think `self.reconnect()` should be added when error handler occurs a key exception.
Thanks.

https://github.com/nlsdfnbch/btfxwss/blob/master/btfxwss/connection.py#L424

**Comment by nlsdfnbch** [comment]
Hey @Changsung ,
thanks for reporting this.
However, this is a bug - there should be only a reconnect attempt if we know why we're reconnecting (this includes timeouts, server errors or reconnect messages from the API). 
For your case, this simply means we're missing a handler for `code:"2000"`. This doesn't require a reconnect, as the message indicates that the `user` parameter is invalid - hence, this wouldn't be resolved by reconnecting, since the `user` parameter is given on instantiation of the `Btfxwss` class, not on `start()`/`connect()`.

**Comment by Changsung** [comment]
Hello @nlsdfnbch 
Thanks for your comment. I read over the fix that you just committed in connection.py (https://github.com/nlsdfnbch/btfxwss/blob/master/btfxwss/connection.py#L400).
In my case, the user invalid error was distributed into error_handler and logged as an error, not info_handler. It means that the event data whose error code is 20000 is categorized as an event, not an info. So, I think your fix won't cover the 20000 error code and it should be in error_handler function.

By the way, I do not understand what the error code means. Could you explain the meaning if you may know? The error code abruptly occurred while the trade loop worked really well for at least 6 hours.

Regards

**Comment by Changsung** [comment]
I attach the log below for your information.
`ERROR:btfxwss.connection:Received unknown error Code in message {'msg': 'user: invalid', 'code': 20000}! Reconnecting..`
Thanks

**Comment by nlsdfnbch** [comment]
Hm. You're right - since I filter for `code` to assert if a message is an error, this ends up in the error handler. However, according to a ticket I opened with them a while back, `1X` are errors, `2X` are info messages. 
But I saw just now that they apparently changed that - since that pattern does not hold true anymore, according to their glossary. Sorry about that! I'm on this right now.

As to why the message popped up 6 hours is, I can only guess - perhaps it _does_ require a reconnect, as this could be their way of telling you that they'd like you to reconnect. But this just a guess - I'll contact support about this. You should too, they tend to take forever to reply, lately.
